In [ ]:
#mounting to google
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
import os
!find "/content/drive/My Drive" -name "carprice.csv"

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/carprices.csv')
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [ ]:
df.shape

(13, 4)

In [ ]:
df.isnull().sum()

Car Model        0
Mileage          0
Sell Price($)    0
Age(yrs)         0
dtype: int64

In [ ]:
df.dtypes

Car Model        object
Mileage           int64
Sell Price($)     int64
Age(yrs)          int64
dtype: object

##Using the pandas dummies

In [ ]:
dum = pd.get_dummies(df['Car Model']).astype(int)
dum

    Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [ ]:
merge = pd.concat([df,dum],axis='columns')
merge

                Car Model  Mileage  ...  BMW X5  Mercedez Benz C class
0                  BMW X5    69000  ...       1                      0
1                  BMW X5    35000  ...       1                      0
2                  BMW X5    57000  ...       1                      0
3                  BMW X5    22500  ...       1                      0
4                  BMW X5    46000  ...       1                      0
5                 Audi A5    59000  ...       0                      0
6                 Audi A5    52000  ...       0                      0
7                 Audi A5    72000  ...       0                      0
8                 Audi A5    91000  ...       0                      0
9   Mercedez Benz C class    67000  ...       0                      1
10  Mercedez Benz C class    83000  ...       0                      1
11  Mercedez Benz C class    79000  ...       0                      1
12  Mercedez Benz C class    59000  ...       0                      1

[13 rows x 7 columns]

In [ ]:
final = merge.drop(['Car Model'],axis='columns')
final

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0     69000          18000         6        0       1                      0
1     35000          34000         3        0       1                      0
2     57000          26100         5        0       1                      0
3     22500          40000         2        0       1                      0
4     46000          31500         4        0       1                      0
5     59000          29400         5        1       0                      0
6     52000          32000         5        1       0                      0
7     72000          19300         6        1       0                      0
8     91000          12000         8        1       0                      0
9     67000          22000         6        0       0                      1
10    83000          20000         7        0       0                      1
11    79000          21000         7        0       0                      1
12    59000          33000         5        0       0                      1

In [ ]:
final = final.drop(['Mercedez Benz C class'],axis='columns')
final

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [ ]:
x = final.drop(['Sell Price($)'],axis='columns')
x

    Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6        0       1
1     35000         3        0       1
2     57000         5        0       1
3     22500         2        0       1
4     46000         4        0       1
5     59000         5        1       0
6     52000         5        1       0
7     72000         6        1       0
8     91000         8        1       0
9     67000         6        0       0
10    83000         7        0       0
11    79000         7        0       0
12    59000         5        0       0

In [ ]:
y = final['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [ ]:
model = linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [ ]:
model.predict(x)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [ ]:
model.score(x,y)

0.9417050937281082

In [ ]:
model.predict([[5000,5,0,0,0]])

array([3089417.67199257])

##Label encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dfle = df
dfle['Car Model'] = le.fit_transform(dfle['Car Model'])
dfle

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

##One-hot encoding

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/carprices.csv')
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('Car Model',OneHotEncoder(),[0])],remainder='passthrough')
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('Car Model', OneHotEncoder(), [0])])

In [ ]:
X = df.drop(['Sell Price($)'],axis='columns')
X

                Car Model  Mileage  Age(yrs)
0                  BMW X5    69000         6
1                  BMW X5    35000         3
2                  BMW X5    57000         5
3                  BMW X5    22500         2
4                  BMW X5    46000         4
5                 Audi A5    59000         5
6                 Audi A5    52000         5
7                 Audi A5    72000         6
8                 Audi A5    91000         8
9   Mercedez Benz C class    67000         6
10  Mercedez Benz C class    83000         7
11  Mercedez Benz C class    79000         7
12  Mercedez Benz C class    59000         5

In [ ]:
Y = df['Sell Price($)']
Y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [ ]:
X = ct.fit_transform(X)
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [ ]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X,Y)

LinearRegression()

In [ ]:
model.predict([[0,1,0,69000,5]])

array([20037.72599202])

In [ ]:
model.predict([[0,0,1,45000,4]])

array([36991.31721061])

In [ ]:
model.predict([[1,0,0,86000,7]])

array([15365.40972059])

In [ ]:
model.score(X,Y)

0.9417050937281083