In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
df = pd.read_csv('/content/drive/MyDrive/hiring.csv')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [16]:
df.shape

(8, 4)

In [17]:
num_words = {
    'zero':0,
    'one':1,
    'two':2,
    'three':3,
    'four':4,
    'five':5,
    'six':6,
    'seven':7,
    'eight':8,
    'nine':9,
    'ten':10,
    'eleven':11
}
df['experience'] = df['experience'].map(num_words)
df['experience'] = df['experience'].fillna(0)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [18]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].median())

df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)

In [19]:
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [20]:
X = df[['experience',
        'test_score(out of 10)',
        'interview_score(out of 10)']]

y = df['salary($)']

In [21]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X, y)

LinearRegression()

In [23]:
import pandas as pd

new_data = pd.DataFrame({
    'experience': [2],
    'test_score(out of 10)': [9],
    'interview_score(out of 10)': [6]
})

prediction = model.predict(new_data)

print(prediction)

[53205.96797671]

In [24]:
import pandas as pd

new_data = pd.DataFrame({
    'experience': [12],
    'test_score(out of 10)': [10],
    'interview_score(out of 10)': [10]
})

prediction = model.predict(new_data)

print(prediction)

[92002.18340611]